# Generated by Django 5.2.1 on 2025-06-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
                ('guests', models.IntegerField()),
                ('comments', models.CharField(max_length=1000)),
            ],
        ),
    ]
